{% set name = "django-reversion-compare" %}
{% set version = "0.8.6" %}
{% set sha256 = "c7b08298b5ce93ccd07a639c6506842649e5f4efd8ffd53317a08323456add15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - django >=1.8
    - django-reversion >=2.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - reversion_compare
    - reversion_compare_tests

about:
  home: https://github.com/jedie/django-reversion-compare
  license: GPLv3
  license_family: GPL3
  license_file: LICENSE
  summary: 'Add compare view to django-reversion for comparing two versions of a reversion model.'
  description: 
    django-reversion-compare is an extension to django-reversion that provides a history compare 
    view to compare two versions of a model which is under reversion.
  doc_url: https://github.com/jedie/django-reversion-compare
  dev_url: https://github.com/jedie/django-reversion-compare

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
