{% set name = "django-reversion-compare" %}
{% set version = "0.9.1" %}
{% set sha256 = "ab19e69dee42ba3bf2a49d1968fd7b9a6d71ce9106d078b1e97ee95844035c84" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - django >=1.8
    - django-reversion >=2.0

test:
  imports:
    - reversion_compare
    - reversion_compare_tests

about:
  home: https://github.com/jedie/django-reversion-compare
  license: GPLv3
  license_family: GPL3
  license_file: LICENSE
  summary: 'Add compare view to django-reversion for comparing two versions of a reversion model.'
  description: 
    django-reversion-compare is an extension to django-reversion that provides a history compare 
    view to compare two versions of a model which is under reversion.
  doc_url: https://github.com/jedie/django-reversion-compare
  dev_url: https://github.com/jedie/django-reversion-compare

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
