travis:
  secure:
    BINSTAR_TOKEN: InS1FEpOS92GSVh3BCYp3RZLv08/J/c73aZPlVMcd+izdNBadeNgetvBjCpR7Wi9AhmzsSNFzNm5Hcgpw2v1+blcG7BzrkoKko9JppA17LdBIUAHh4l3W1M9o5QGYI1jn9ZAvusZr1Lu4YEqYMnZAK2W4Yyuy6dQaOMZHCDIOGZjZUuM/eibBb+zBZFscE7IsyO2J6TUGUcDfW0i4vXBPD8EddLlPphFaP1SHpBdxFmuXr7EB2O3Ve1TY4OLcgHgTToxasaMG8TNRpnAI+cUk1LCxgDZX+A6fpdm65Lfh+fmBFZk7kAnbwcMtXeDG93qzolQMLHGZgDe690UfAaTAS08QLKsGoXPjcKa7tlqOf1/e6M7D7iiIdG8DOvMuzUPPL0GIUXWFchwld7V43BWIGd97pMcoPe/vGm3CW4gSlUqXJFsnCnZeJnexWgRTaXmATeNoLZISZMPQaozgS+8sohO7qiyDBKK9P225jQ+WAp4AGA/6zUgHOUws6UUY7ZGji+Xd9EPOBqbAwm8Ge7XMbVQ89pSgIKN6JYTHdnJWG+aeLjpG7blopH/pLaNXYg2jVRB62QoZHoeROWLRcm4vjHsdIIucibQ0A5ovY392SvEKRyffZgIkvHF9SujNmZhKBSk8q2tyirr1IHTQyef2jAFzTos0HK3ru2cFfDdUHo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
