travis:
  secure:
    BINSTAR_TOKEN: 0o9T35UT/DBHfIsByrx4A9Fb4Jo4jIM4zar8YwZv7GCYghpO7MzfRLBXCfpgnTWsZq2qnGrZTyoHMY2ruTXJvO7JxwKq7Q/CQaBe/rBrf6LuebICHDe0aF9SAlprH+WG0uYuX/TpnjhVOQjkhq88Jpv5ugflzcK0HYRJozFeFGzPfqEi8bmsUxD2VHo5Fz6rnGmdJkepzCQQvxRppM4Z3RtL5g24fUvstlFUER7mvZ5/BoDIzr6EBVEg/8BbT2u68AsBxaMFcsp3/+Y6MsSSlSkwJx/cwd7RGK+Ycae04YPdZaypWkoLiTMJzPbjefr2lBJ/O0IzjAwoM53/u7CIwpEH65zeb6VRXneZ61EibmD1jOSESW6eh0iuwqjsVc7l1IwjCD2HkmPEBDdoBhAtQkVpLMEAcbpEitGo1NWmkh9JOeTDYhaQ+PR04EznkkR7zs62poNbwunSmoaXaZaEOTmuyL285oQf7LjymMlCdHuR4Gk5MH7uJfPvk/VzERQjX3NHWTYWk0eqv3bF3WJcGIB6Xx5mvbSRWAPfEkt9ILQ8wQSztnc+Tpa2xglcF6DyDp6e/oN77WV/u3qISq2c+PWVAvnPUxmjlgtKKBD4+u2Tw6QDmczVS5+yxmnuctW8WV+S2FWRfyTs8PDScxtPuRqX+iue4QehFQNX3sclhvc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
